---
- name: Base image creation for docker container
  hosts: local
  gather_facts: true
  remote_user: root
  tasks:
       - name: Pull CentOS-7 base image for container
         docker_container:
           name: bhge-centos-7
           image: "centos:7"
           detach: yes
           tty: yes
           state: started

       - name: Copy files from host to container
         command: docker cp /home/perfbhi/docker/Source bhge-centos-7:/Source
         become: yes

       - name: Install additional packages inside container to support compilation
         command: docker exec bhge-centos-7 sh -c /Source/yum_install.sh
         become: yes

       - name: Install and compile packages insider container
         command: docker exec bhge-centos-7 sh -c /Source/source_compile.sh
         become: yes
